---
name: pyfive
channels:
  - conda-forge
  - nodefaults

dependencies:
  # core dependencies
  - numpy >=2
  - python >=3.10
  - typing_extensions
  # testing dependencies
  - dask
  - flask
  - flask-cors
  - h5netcdf
  - h5py  # link to same hdf5 lib with netcdf4
  - moto
  - netcdf4 !=1.7.4  # github.com/Unidata/netcdf4-python/issues/1464
  - pre-commit  # with ruff and mypy
  - pytest
  - pytest-cov
  - pytest-html
  - pytest-rerunfailures
  - pytest-xdist
  - python-neo-lzf  # built from pypi.org/project/python-neo-lzf/
  - s3fs >=2025.9.0
  # documentation dependencies
  - autodocsumm
  - sphinx
  - sphinx_rtd_theme
